name: Release

on:
  push:
    tags:
      - 'v*'  # e.g. v1.0.0

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build project
        run: |
          python3 build.py

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: artifacts/

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/*
          body: |
            Tain CLI v0.6.1
            - Built for `aarch64-unknown-linux-gnu`
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
